### ISSUE TITLE
Jetty team members should have the ability to open / manage issues on this jetty/.eclipsefdn repo

### ISSUE THREAD

**Issue by joakime** [jetty/.eclipsefdn#9]
Currently this repo https://github.com/jetty/.eclipsefdn lacks the ability to manage issues that should eventually be applied at an organizational level (possibly in an otterdog configuration PR)

@netomi Can issues on this repo be opened to the Jetty team (so that we can assign / label / close)?
The existing rights for Pull Requests seem sane, so I don't see any need for extra rights there.

**Comment by joakime** [comment]
Filed issue at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3851 for this as well.

**Comment by netomi** [comment]
So the default setup is that project-leads have triage permissions on this repo so that they can do what you describe.
Our sync script setup these permissions, so if I give that also to committers it will get overwritten the next time it runs.

You request makes sense, I will think about a solution.

**Comment by jmcc0nn3ll** [comment]
think this is working now
